version: '3.7'
services:
  course_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_backend_unmsm
    ports: -3001:3000
    depends_on:
      - course_postgres_db
    env_file:
      - .env
    networks:
      microservices_network:
        aliases:
          - course_backend_network

    course_postgres_db:
      image: postgres:14.7-alpine
      container_name: course_db_unmsm
      env_file:
        - .env
      ports:
        - 5432:5432
      volumes:
        - ./.docker-conf/course-postgres/data/:/var/lib/postgres/data
      networks:
        microservices_network:
          aliases:
            - course_db_network

networks:
  microservices_network:
    driver: bridge
    name: microservice-network